import './styles/globals.css'

// Atoms: the generic building blocks — every control, overlay, navigation, layout and
// feedback component, grouped by role. One component does one job, however much it is
// composed of inside (DatePicker = trigger + Popover + Calendar is still one control).
// Atoms never import from fragments (tests/structure.test.ts enforces it).

export * from './components/atoms/actions/button'
export * from './components/atoms/actions/copy-button'
export * from './components/atoms/actions/toggle'
export * from './components/atoms/actions/toggle-group'

export * from './components/atoms/data-display/accordion'
export * from './components/atoms/data-display/avatar'
export * from './components/atoms/data-display/chart'
export * from './components/atoms/data-display/collapsible'
export * from './components/atoms/data-display/kbd'
export * from './components/atoms/data-display/table'

export * from './components/atoms/feedback/alert'
export * from './components/atoms/feedback/badge'
export * from './components/atoms/feedback/banner'
export * from './components/atoms/feedback/progress'
export * from './components/atoms/feedback/shimmering-loader'
export * from './components/atoms/feedback/skeleton'
export * from './components/atoms/feedback/sonner'
export * from './components/atoms/feedback/spinner'

export * from './components/atoms/forms/calendar'
export * from './components/atoms/forms/checkbox'
export * from './components/atoms/forms/combobox'
export * from './components/atoms/forms/data-input'
export * from './components/atoms/forms/date-field'
export * from './components/atoms/forms/date-picker'
export * from './components/atoms/forms/file-upload'
export * from './components/atoms/forms/form'
export * from './components/atoms/forms/input'
export * from './components/atoms/forms/input-otp'
export * from './components/atoms/forms/label'
export * from './components/atoms/forms/multi-select'
export * from './components/atoms/forms/number-input'
export * from './components/atoms/forms/password-input'
export * from './components/atoms/forms/radio-group'
export * from './components/atoms/forms/select'
export * from './components/atoms/forms/slider'
export * from './components/atoms/forms/switch'
export * from './components/atoms/forms/textarea'
export * from './components/atoms/forms/time-picker'

export * from './components/atoms/layout/aspect-ratio'
export * from './components/atoms/layout/box'
export * from './components/atoms/layout/card'
export * from './components/atoms/layout/container'
export * from './components/atoms/layout/flex'
export * from './components/atoms/layout/floating-plate'
export * from './components/atoms/layout/grid'
export * from './components/atoms/layout/layout-types'
export * from './components/atoms/layout/resizable'
export * from './components/atoms/layout/scroll-area'
export * from './components/atoms/layout/separator'
export * from './components/atoms/layout/stack'

export * from './components/atoms/navigation/breadcrumb'
export * from './components/atoms/navigation/command'
export * from './components/atoms/navigation/menubar'
export * from './components/atoms/navigation/navigation-menu'
export * from './components/atoms/navigation/pagination'
export * from './components/atoms/navigation/sidebar'
export * from './components/atoms/navigation/stepper'
export * from './components/atoms/navigation/tabs'
export * from './components/atoms/navigation/text-link'

export * from './components/atoms/overlay/alert-dialog'
export * from './components/atoms/overlay/confirm-popover'
export * from './components/atoms/overlay/context-menu'
export * from './components/atoms/overlay/dialog'
export * from './components/atoms/overlay/drawer'
export * from './components/atoms/overlay/dropdown-menu'
export * from './components/atoms/overlay/hover-card'
export * from './components/atoms/overlay/popover'
export * from './components/atoms/overlay/sheet'
export * from './components/atoms/overlay/tooltip'

// Fragments: ready-made, opinionated compositions of atoms for a specific use — form
// field layouts, data table, metric card, error display, code block, theme toggle, …

export * from './components/fragments/admonition'
export * from './components/fragments/form-fields'
export * from './components/fragments/form-item-layout'
export * from './components/fragments/info-tooltip'
export * from './components/fragments/empty-state'
export * from './components/fragments/error-display'
export * from './components/fragments/metric-card'
export * from './components/fragments/data-table'
export * from './components/fragments/code-block'
export * from './components/fragments/timestamp-info'
export * from './components/fragments/status-code'
export * from './components/fragments/theme-toggle'
export * from './components/fragments/glass-panel'
export * from './components/fragments/row'

export * from './providers'
export * from './theme'

export { cn } from './lib/utils'
export type { ClassValue } from './lib/utils'
export { SIZE, SIZE_VARIANTS, SIZE_VARIANTS_DEFAULT } from './lib/constants'
export { copyToClipboard } from './lib/copy-to-clipboard'
